//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pwtter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pwtter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pwtter-v1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PwAppName {
            get {
                return ResourceManager.GetString("PwAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5e81a06cf793c45ca6c393a97113bbb4a61abeebbe4a52743c62333fbadbfad0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PwClientKey {
            get {
                return ResourceManager.GetString("PwClientKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   861368f6e9c5a42e31e8da00f378aaf4d3079e6be476e071ae3c9afe8548e1bb に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PwClientSecret {
            get {
                return ResourceManager.GetString("PwClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ORW7Ow6miLWNPxoXfU0CIaoNN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TwConsumerKey {
            get {
                return ResourceManager.GetString("TwConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   gh2LE6Y9juSjlP0lHc823z4DhZuO8K0xMJRXIDTJ43wlcnSvEO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TwConsumerSecret {
            get {
                return ResourceManager.GetString("TwConsumerSecret", resourceCulture);
            }
        }
    }
}
